### ISSUE TITLE
Redirects return blank page with HTTP 200 status

### ISSUE THREAD

**Issue by zimozy** [christianklisch/slim-minify#11]
I couldn't perform redirects:
`return $response->withRedirect('/page');`
I'd get a blank page with an HTTP 200 status code.

I was able to fix this on my machine by changing 
`$next($request,$response);`
to
`$response = $next($request,$response);`

(Since the Response is immutable as per the [user guide](https://www.slimframework.com/docs/v3/objects/response.html).)

**Comment by jissereitsma** [comment]
Thanks @zimozy for finding this. I bumped into the same issue. @christianklisch, is this still something you want to maintain? Middleware under Slim 3 requires the solution that @zimozy suggested.
