### ISSUE TITLE
Support slim v4

### ISSUE THREAD

**Issue by Jebati** [christianklisch/slim-minify#14]
```
$app = AppFactory::createFromContainer($container);
$app->add(new \Slim\Middleware\Minify());
```

`Fatal error: Uncaught TypeError: Argument 2 passed to Slim\Middleware\Minify::__invoke() must be an instance of Psr\Http\Message\ResponseInterface, instance of Slim\Routing\RouteRunner given, called in /home/site/vendor/slim/slim/Slim/MiddlewareDispatcher.php on line 313 and defined in /home/site/vendor/christianklisch/slim-minify/src/Slim/Middleware/Minify.php:61 Stack trace: #0 /home/site/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Slim\Middleware\Minify->__invoke(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) #1 /home/site/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request)) #2 /home/site/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #3 /home/site/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request)) #4 /home/site/public/index.php(138): Slim\App->run() #5 {main} thrown in /home/site/vendor/christianklisch/slim-minify/src/Slim/Middleware/Minify.php on line 61`

![image](https://user-images.githubusercontent.com/24898536/111471984-9144f300-873a-11eb-868b-25ba2a81d392.png)

**Comment by christianklisch** [comment]
please test with version 0.7.0

**Comment by christianklisch** [comment]
fixed & closed
